import {
  MOON_CONTRACT,
  MOON_CONTRACT_SPECIES,
  MOON_CONTRACT_WAR,
  TESNET_CONTRACT,
  TESNET_CONTRACT_SPECIES,
  TESNET_CONTRACT_WAR,
} from "./constants/contracts";
import {
  API_MAINET,
  API_TESNET,
  IPFS_MAINET,
  IPFS_TESNET,
  URL_EXPLORER_MAINET,
  URL_EXPLORER_TESNET,
  URL_MAINET,
  URL_WAR_MAINET,
  URL_WAR_TESNET,
} from "./constants/endpoints";
import { METHODS_MAINET, METHODS_TESNET } from "./constants/methodsSwap";
import { PAIRS_MAINNET, PAIRS_TESTNET } from "./constants/pair";
import { TOKEN_MAINNET, TOKEN_TESTNET } from "./constants/tokens";
import {
  CHAIN_ID_MAINNET,
  CHAIN_ID_TESTNET,
  WEB3_NETWORKWAR_MAINNET,
  WEB3_NETWORK_MAINNET,
  WEB3_NETWORK_TESTNET,
} from "./constants/networks";

/**
 * @ENTORNO
 */
export const PRODUCTION = true;

/**
 * @NETWORKS
 * @BLOCKCHAIN
 */
export const CHAIN_ID = PRODUCTION ? CHAIN_ID_MAINNET : CHAIN_ID_TESTNET;

export const NETWORK_MAINNET = PRODUCTION ? "mainnet" : "testnet";

export const WEB3_NETWORK = PRODUCTION
  ? WEB3_NETWORK_MAINNET
  : WEB3_NETWORK_TESTNET;

export const WEB3_NETWORKWAR = PRODUCTION
  ? WEB3_NETWORKWAR_MAINNET
  : WEB3_NETWORK_TESTNET;

/**
 * @CONTRACTS
 * @ABI
 * @TOKENS
 */

export const CONTRACTS = PRODUCTION ? MOON_CONTRACT : TESNET_CONTRACT;
export const CONTRACTS_WAR = PRODUCTION
  ? MOON_CONTRACT_WAR
  : TESNET_CONTRACT_WAR;
export const CONTRACTS_SPECIES = PRODUCTION
  ? MOON_CONTRACT_SPECIES
  : TESNET_CONTRACT_SPECIES;

export const ROUTER_METHODS = PRODUCTION ? METHODS_MAINET : METHODS_TESNET;

export const TOKENS = PRODUCTION ? TOKEN_MAINNET : TOKEN_TESTNET;
export const PAIRS = PRODUCTION ? PAIRS_MAINNET : PAIRS_TESTNET;

/**
 * @ENDPOINTS
 */
export const URL = PRODUCTION ? URL_MAINET : URL_MAINET;
export const URL_WAR = PRODUCTION ? URL_WAR_MAINET : URL_WAR_TESNET;
export const URL_EXPLORER = PRODUCTION
  ? URL_EXPLORER_MAINET
  : URL_EXPLORER_TESNET;
export const API = PRODUCTION ? API_MAINET : API_TESNET;
export const IPFS = PRODUCTION ? IPFS_MAINET : IPFS_TESNET;
