import Head from "next/head";
import { AuthContextProvider } from "../context/AuthContext";
import "../styles/globals.css";
import "../styles/main.scss";

function MyApp({ Component, pageProps }) {
  return (
    <AuthContextProvider>
      <Head>
        <title>Renian | Registro Nacional de Identidad Animal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/renian.ico" />
      </Head>
      <Component {...pageProps} />
    </AuthContextProvider>
  );
}

export default MyApp;
