import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Renian | Registro Nacional de Identidad Animal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/renian.ico" />
      </Head>
      <h1>Bye World</h1>
    </div>
  );
}
